// Code generated by cmd/browsercapture-manifest; DO NOT EDIT.
// Source: smartaccounts-browser-discovery-protocol-v1 (redacted resource IDs/coverage and validator bounds).
package smartaccountssync

const (
	BrowserDiscoveryProtocolVersion        = "smartaccounts-browser-discovery-protocol-v1"
	BrowserDiscoveryProtocolSHA256         = "94d8793b474ca1c57e722c57dc608031aed70dced93f31437c54a3310b5a1553"
	BrowserDiscoveryManifestVersion        = "smartaccounts-brave-ui-v2"
	BrowserDiscoveryContractVersion        = "smartaccounts-brave-discovery-contract-v1"
	BrowserDiscoveryMaxReceiptBytes        = 1048576
	BrowserDiscoveryMaxHeaderNames         = 128
	BrowserDiscoveryMaxHeaderNameUTF8Bytes = 120
	BrowserDiscoveryMaxControlIDBytes      = 80
	BrowserDiscoveryMaxPathBytes           = 512
	BrowserCaptureMaxResourceBytes         = 33554432
	BrowserCaptureManifestVersion          = BrowserDiscoveryManifestVersion
)

type browserDiscoveryProtocolResource struct {
	ID       string
	Coverage string
}

var browserDiscoveryProtocolResources = [...]browserDiscoveryProtocolResource{
	{ID: "account_turnover", Coverage: "export_csv"},
	{ID: "annual_report", Coverage: "page_only"},
	{ID: "articles", Coverage: "export_csv"},
	{ID: "balance_sheet", Coverage: "export_csv"},
	{ID: "bank_payments", Coverage: "export_csv"},
	{ID: "cash_flow_statement", Coverage: "export_csv"},
	{ID: "cash_payments", Coverage: "export_csv"},
	{ID: "client_invoices", Coverage: "export_csv"},
	{ID: "client_offers", Coverage: "export_csv"},
	{ID: "client_orders", Coverage: "export_csv"},
	{ID: "clients", Coverage: "export_csv"},
	{ID: "depreciations", Coverage: "export_csv"},
	{ID: "fixed_asset_depreciation_report", Coverage: "export_csv"},
	{ID: "fixed_assets", Coverage: "export_csv"},
	{ID: "general_ledger", Coverage: "export_csv"},
	{ID: "income_statement", Coverage: "export_csv"},
	{ID: "journal_entries", Coverage: "export_csv"},
	{ID: "other_reports", Coverage: "page_only"},
	{ID: "salaries", Coverage: "export_csv"},
	{ID: "tsd_returns", Coverage: "export_csv"},
	{ID: "vat_returns", Coverage: "export_csv"},
	{ID: "vendor_invoices", Coverage: "export_csv"},
	{ID: "vendor_orders", Coverage: "export_csv"},
	{ID: "vendors", Coverage: "export_csv"},
	{ID: "wage_reports", Coverage: "page_only"},
	{ID: "warehouse_inventory", Coverage: "page_only"},
	{ID: "warehouse_movements", Coverage: "export_csv"},
	{ID: "warehouse_movements_report", Coverage: "page_only"},
	{ID: "warehouses", Coverage: "page_only"},
	{ID: "worker_absences", Coverage: "page_only"},
	{ID: "workers", Coverage: "export_csv"},
}

func browserDiscoveryResourceIDs() []string {
	ids := make([]string, len(browserDiscoveryProtocolResources))
	for index, resource := range browserDiscoveryProtocolResources {
		ids[index] = resource.ID
	}
	return ids
}

func browserDiscoveryResourceCoverage(resourceID string) (string, bool) {
	for _, resource := range browserDiscoveryProtocolResources {
		if resource.ID == resourceID {
			return resource.Coverage, true
		}
	}
	return "", false
}
