package smartaccountssync

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
)

const (
	BrowserCaptureWorkflowVersion  = "smartaccounts-browser-workflow-v1"
	BrowserCapturePlanVersion      = "smartaccounts-browser-capture-plan-v1"
	BrowserCaptureFromDatePolicy   = "OWNER_EXPLICIT_FROM_DATE"
	BrowserCaptureWorkflowReady    = "READY_FOR_CONSENT"
	BrowserCaptureWorkflowIssued   = "CAPTURE_ISSUED"
	// BrowserCaptureProvenGeneralLedgerCSV is the only browser resource that
	// can enter the GL-authoritative canonical path. The similarly named
	// journal_entries grid is summary-only evidence and is never capture/plan
	// eligible.
	BrowserCaptureProvenGeneralLedgerCSV = BrowserGeneralLedgerResourceID
)

var (
	ErrBrowserCaptureWorkflowUnavailable = errors.New("SmartAccounts browser capture workflow is unavailable")
	ErrBrowserCaptureWorkflowNotFound    = errors.New("SmartAccounts browser capture workflow was not found for this tenant")
	ErrBrowserCaptureWorkflowNotPaired   = errors.New("SmartAccounts browser source is not paired to this tenant")
	ErrBrowserCaptureWorkflowInvalid     = errors.New("SmartAccounts browser capture workflow boundary is invalid")
)

// BrowserCaptureWorkflowRequest includes the sole operator-controlled capture
// boundary: the historical start date. The end/cutoff and resource selection
// are generated by OA, never copied from a page or extension message.
type BrowserCaptureWorkflowRequest struct {
	SourceCompanyID          string `json:"source_company_id"`
	FromInclusive            string `json:"from_inclusive"`
	TransferConsentConfirmed bool   `json:"transfer_consent_confirmed"`
}

// BrowserCapturePlan is safe, immutable metadata. It proves only the reviewed
// SmartAccounts General Ledger CSV route; other browser-visible data, including
// the journal_entries summary grid, remains out of scope until separately
// reviewed.
type BrowserCapturePlan struct {
	Version             string              `json:"version"`
	FromDatePolicy      string              `json:"from_date_policy"`
	RunID               string              `json:"run_id,omitempty"`
	TenantID            string              `json:"tenant_id"`
	SourceCompanyID     string              `json:"source_company_id"`
	ManifestVersion     string              `json:"manifest_version"`
	Scope               BrowserCaptureScope `json:"scope"`
	EligibleResourceIDs []string            `json:"eligible_resource_ids"`
}

// BrowserCaptureWorkflow is an idempotent server record keyed by a selected
// tenant/source/history-start policy. It is not a relay authorization.
type BrowserCaptureWorkflow struct {
	ID              string
	TenantID        string
	SourceCompanyID string
	FromInclusive   string
	ToInclusive     string
	CutoffAt        time.Time
	CaptureRunID    string
	Status          string
	CreatedBy       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// BrowserCaptureWorkflowStatus is owner-safe and intentionally lacks any
// raw capability. Capture is returned only from the current action-time
// consent request and should be passed directly into extension memory.
type BrowserCaptureWorkflowStatus struct {
	WorkflowID string                `json:"workflow_id"`
	Status     string                `json:"status"`
	Plan       BrowserCapturePlan    `json:"plan"`
	Capture    *BrowserCaptureIssue  `json:"capture,omitempty"`
	Progress   *BrowserCaptureStatus `json:"progress,omitempty"`
}

type BrowserCaptureWorkflowStore interface {
	FindOrCreateBrowserCaptureWorkflow(context.Context, BrowserCaptureWorkflow) (*BrowserCaptureWorkflow, bool, error)
	GetBrowserCaptureWorkflow(context.Context, string, string) (*BrowserCaptureWorkflow, error)
	SetBrowserCaptureWorkflowRun(context.Context, string, string, string, time.Time) (*BrowserCaptureWorkflow, error)
}

// BrowserCaptureWorkflowService composes paired-source validation, one
// server-derived capture plan, and a short-lived browser capability. It has no
// SmartAccounts client and cannot post financial data.
type BrowserCaptureWorkflowService struct {
	store    BrowserCaptureWorkflowStore
	controls BrowserCaptureControlReader
	captures *BrowserCaptureService
	now      func() time.Time
	newID    func() string
	newRun   func() string
}

func NewBrowserCaptureWorkflowService(store BrowserCaptureWorkflowStore, controls BrowserCaptureControlReader, captures *BrowserCaptureService) *BrowserCaptureWorkflowService {
	return &BrowserCaptureWorkflowService{store: store, controls: controls, captures: captures, now: time.Now, newID: uuid.NewString, newRun: uuid.NewString}
}

// Start creates (or retrieves) the exact selected workflow. A capability is
// created or rotated only when the owner affirms transfer consent in this
// request. Retry preserves the same workflow and run; it never starts a
// second capture for the same tenant/source/history-start selection.
func (s *BrowserCaptureWorkflowService) Start(ctx context.Context, tenantID, actor string, request BrowserCaptureWorkflowRequest) (*BrowserCaptureWorkflowStatus, error) {
	if s == nil || s.store == nil || s.controls == nil || s.captures == nil || s.newID == nil || s.newRun == nil || !safeBridgeID(strings.TrimSpace(tenantID)) {
		return nil, ErrBrowserCaptureWorkflowUnavailable
	}
	tenantID = strings.TrimSpace(tenantID)
	request.SourceCompanyID = strings.TrimSpace(request.SourceCompanyID)
	request.FromInclusive = strings.TrimSpace(request.FromInclusive)
	if !validBrowserCaptureWorkflowRequest(request) {
		return nil, ErrBrowserCaptureWorkflowInvalid
	}
	now := s.currentTime()
	from, _ := time.Parse(time.DateOnly, request.FromInclusive)
	if from.After(time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)) {
		return nil, ErrBrowserCaptureWorkflowInvalid
	}
	control, err := s.controls.Get(ctx, tenantID, request.SourceCompanyID)
	if err != nil || control == nil || !isBrowserSessionReference(control.SecretReference) {
		return nil, ErrBrowserCaptureWorkflowNotPaired
	}
	workflow, _, err := s.store.FindOrCreateBrowserCaptureWorkflow(ctx, BrowserCaptureWorkflow{
		ID: s.newID(), TenantID: tenantID, SourceCompanyID: request.SourceCompanyID,
		FromInclusive: request.FromInclusive, ToInclusive: now.Format(time.DateOnly), CutoffAt: now,
		Status: BrowserCaptureWorkflowReady, CreatedBy: strings.TrimSpace(actor), CreatedAt: now, UpdatedAt: now,
	})
	if err != nil || workflow == nil || !validBrowserCaptureWorkflow(*workflow) {
		return nil, ErrBrowserCaptureWorkflowUnavailable
	}
	result := workflowStatus(workflow)
	if !request.TransferConsentConfirmed {
		return result, nil
	}

	runID := workflow.CaptureRunID
	if runID == "" {
		runID = s.newRun()
		if !validBrowserPairingID(runID) {
			return nil, ErrBrowserCaptureWorkflowUnavailable
		}
		workflowID := workflow.ID
		workflow, err = s.store.SetBrowserCaptureWorkflowRun(ctx, tenantID, workflowID, runID, now)
		if err != nil || workflow == nil || workflow.CaptureRunID != runID {
			// A concurrent same-policy request may have reserved the run after
			// our read. Re-read only the tenant-scoped workflow and reuse that
			// immutable run; never attempt to overwrite it with a second run.
			workflow, err = s.store.GetBrowserCaptureWorkflow(ctx, workflowID, tenantID)
			if err != nil || workflow == nil || workflow.CaptureRunID == "" {
				return nil, ErrBrowserCaptureWorkflowUnavailable
			}
			runID = workflow.CaptureRunID
		}
	}
	issue, err := s.captures.IssueForRun(ctx, tenantID, actor, runID, BrowserCaptureStartRequest{
		SourceCompanyID: workflow.SourceCompanyID, ManifestVersion: BrowserCaptureManifestVersion, Scope: scopeForBrowserCaptureWorkflow(workflow),
	})
	if err != nil {
		return nil, ErrBrowserCaptureWorkflowUnavailable
	}
	workflow.Status = BrowserCaptureWorkflowIssued
	result = workflowStatus(workflow)
	result.Capture = issue
	return result, nil
}

// Status resolves an existing workflow only inside its tenant. It can safely
// project bridge progress but never returns a relay capability after issuance.
func (s *BrowserCaptureWorkflowService) Status(ctx context.Context, tenantID, workflowID string) (*BrowserCaptureWorkflowStatus, error) {
	if s == nil || s.store == nil || s.captures == nil || !safeBridgeID(strings.TrimSpace(tenantID)) || !validBrowserPairingID(workflowID) {
		return nil, ErrBrowserCaptureWorkflowNotFound
	}
	workflow, err := s.store.GetBrowserCaptureWorkflow(ctx, strings.TrimSpace(workflowID), strings.TrimSpace(tenantID))
	if err != nil || workflow == nil || !validBrowserCaptureWorkflow(*workflow) {
		return nil, ErrBrowserCaptureWorkflowNotFound
	}
	result := workflowStatus(workflow)
	if workflow.CaptureRunID == "" {
		return result, nil
	}
	progress, err := s.captures.OwnerStatus(ctx, workflow.TenantID, workflow.CaptureRunID)
	if errors.Is(err, ErrBrowserCaptureUnauthorized) {
		return nil, ErrBrowserCaptureWorkflowNotFound
	}
	if err != nil {
		return nil, ErrBrowserCaptureWorkflowUnavailable
	}
	result.Progress = &progress
	return result, nil
}

func workflowStatus(workflow *BrowserCaptureWorkflow) *BrowserCaptureWorkflowStatus {
	if workflow == nil {
		return nil
	}
	return &BrowserCaptureWorkflowStatus{WorkflowID: workflow.ID, Status: workflow.Status, Plan: BrowserCapturePlan{
		Version: BrowserCapturePlanVersion, FromDatePolicy: BrowserCaptureFromDatePolicy, RunID: workflow.CaptureRunID,
		TenantID: workflow.TenantID, SourceCompanyID: workflow.SourceCompanyID, ManifestVersion: BrowserCaptureManifestVersion,
		Scope: scopeForBrowserCaptureWorkflow(workflow), EligibleResourceIDs: []string{BrowserCaptureProvenGeneralLedgerCSV},
	}}
}

func scopeForBrowserCaptureWorkflow(workflow *BrowserCaptureWorkflow) BrowserCaptureScope {
	if workflow == nil {
		return BrowserCaptureScope{}
	}
	return BrowserCaptureScope{Mode: "partial", FromInclusive: workflow.FromInclusive, ToInclusive: workflow.ToInclusive, CutoffAt: workflow.CutoffAt.UTC().Format(time.RFC3339), ResourceIDs: []string{BrowserCaptureProvenGeneralLedgerCSV}}
}

func validBrowserCaptureWorkflowRequest(request BrowserCaptureWorkflowRequest) bool {
	if !validBrowserSourceCompanyID(request.SourceCompanyID) {
		return false
	}
	_, err := time.Parse(time.DateOnly, strings.TrimSpace(request.FromInclusive))
	return err == nil
}

func validBrowserCaptureWorkflow(workflow BrowserCaptureWorkflow) bool {
	if !validBrowserPairingID(workflow.ID) || !safeBridgeID(workflow.TenantID) || !validBrowserSourceCompanyID(workflow.SourceCompanyID) || workflow.CutoffAt.IsZero() || workflow.CreatedAt.IsZero() || workflow.UpdatedAt.IsZero() || (workflow.Status != BrowserCaptureWorkflowReady && workflow.Status != BrowserCaptureWorkflowIssued) {
		return false
	}
	from, fromErr := time.Parse(time.DateOnly, workflow.FromInclusive)
	to, toErr := time.Parse(time.DateOnly, workflow.ToInclusive)
	if fromErr != nil || toErr != nil || to.Before(from) || workflow.CutoffAt.UTC().Format(time.DateOnly) != workflow.ToInclusive {
		return false
	}
	return workflow.CaptureRunID == "" || validBrowserPairingID(workflow.CaptureRunID)
}

func (s *BrowserCaptureWorkflowService) currentTime() time.Time {
	if s != nil && s.now != nil {
		return s.now().UTC()
	}
	return time.Now().UTC()
}
