// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Tenant struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Slug       string             `db:"slug" json:"slug"`
	SchemaName string             `db:"schema_name" json:"schema_name"`
	Settings   json.RawMessage    `db:"settings" json:"settings"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TenantUser struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	IsDefault bool               `db:"is_default" json:"is_default"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Name         string             `db:"name" json:"name"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VatRate struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	CountryCode string             `db:"country_code" json:"country_code"`
	RateType    string             `db:"rate_type" json:"rate_type"`
	Rate        decimal.Decimal    `db:"rate" json:"rate"`
	Name        string             `db:"name" json:"name"`
	ValidFrom   pgtype.Date        `db:"valid_from" json:"valid_from"`
	ValidTo     pgtype.Date        `db:"valid_to" json:"valid_to"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
