// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToTenant(ctx context.Context, arg *AddUserToTenantParams) error
	CreateTenant(ctx context.Context, arg *CreateTenantParams) (*Tenant, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	CreateVATRate(ctx context.Context, arg *CreateVATRateParams) (*VatRate, error)
	DeactivateTenant(ctx context.Context, id uuid.UUID) error
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetCurrentVATRate(ctx context.Context, arg *GetCurrentVATRateParams) (*VatRate, error)
	GetTenant(ctx context.Context, id uuid.UUID) (*Tenant, error)
	GetTenantBySchemaName(ctx context.Context, schemaName string) (*Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserRole(ctx context.Context, arg *GetUserRoleParams) (string, error)
	GetUserTenants(ctx context.Context, userID uuid.UUID) ([]*GetUserTenantsRow, error)
	GetVATRate(ctx context.Context, id uuid.UUID) (*VatRate, error)
	ListCurrentVATRates(ctx context.Context, countryCode string) ([]*VatRate, error)
	ListTenants(ctx context.Context) ([]*Tenant, error)
	ListVATRates(ctx context.Context, countryCode string) ([]*VatRate, error)
	RemoveUserFromTenant(ctx context.Context, arg *RemoveUserFromTenantParams) error
	SetDefaultTenant(ctx context.Context, arg *SetDefaultTenantParams) error
	SlugExists(ctx context.Context, slug string) (bool, error)
	UpdateTenant(ctx context.Context, arg *UpdateTenantParams) (*Tenant, error)
	UpdateTenantSettings(ctx context.Context, arg *UpdateTenantSettingsParams) (*Tenant, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error
	UpdateVATRate(ctx context.Context, arg *UpdateVATRateParams) (*VatRate, error)
	UserHasTenantAccess(ctx context.Context, arg *UserHasTenantAccessParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
