// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, schema_name, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, schema_name, settings, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	Name       string          `db:"name" json:"name"`
	Slug       string          `db:"slug" json:"slug"`
	SchemaName string          `db:"schema_name" json:"schema_name"`
	Settings   json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg *CreateTenantParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.SchemaName,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateTenant = `-- name: DeactivateTenant :exec
UPDATE tenants
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, schema_name, settings, is_active, created_at, updated_at FROM tenants
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantBySchemaName = `-- name: GetTenantBySchemaName :one
SELECT id, name, slug, schema_name, settings, is_active, created_at, updated_at FROM tenants
WHERE schema_name = $1 AND is_active = true
`

func (q *Queries) GetTenantBySchemaName(ctx context.Context, schemaName string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySchemaName, schemaName)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, schema_name, settings, is_active, created_at, updated_at FROM tenants
WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, schema_name, settings, is_active, created_at, updated_at FROM tenants
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SchemaName,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(SELECT 1 FROM tenants WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, settings = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, schema_name, settings, is_active, created_at, updated_at
`

type UpdateTenantParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Name     string          `db:"name" json:"name"`
	Settings json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg *UpdateTenantParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Settings)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants
SET settings = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, schema_name, settings, is_active, created_at, updated_at
`

type UpdateTenantSettingsParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Settings json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg *UpdateTenantSettingsParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings, arg.ID, arg.Settings)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SchemaName,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
