// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToTenant = `-- name: AddUserToTenant :exec
INSERT INTO tenant_users (tenant_id, user_id, role, is_default)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, user_id) DO UPDATE
SET role = EXCLUDED.role
`

type AddUserToTenantParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Role      string    `db:"role" json:"role"`
	IsDefault bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) AddUserToTenant(ctx context.Context, arg *AddUserToTenantParams) error {
	_, err := q.db.Exec(ctx, addUserToTenant,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.IsDefault,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Name         string `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, name, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, is_active, created_at, updated_at FROM users
WHERE email = $1 AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2
`

type GetUserRoleParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg *GetUserRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.TenantID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserTenants = `-- name: GetUserTenants :many
SELECT t.id, t.name, t.slug, t.schema_name, t.settings, t.is_active, t.created_at, t.updated_at, tu.role, tu.is_default
FROM tenants t
JOIN tenant_users tu ON t.id = tu.tenant_id
WHERE tu.user_id = $1 AND t.is_active = true
ORDER BY tu.is_default DESC, t.name
`

type GetUserTenantsRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	Slug       string             `db:"slug" json:"slug"`
	SchemaName string             `db:"schema_name" json:"schema_name"`
	Settings   json.RawMessage    `db:"settings" json:"settings"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Role       string             `db:"role" json:"role"`
	IsDefault  bool               `db:"is_default" json:"is_default"`
}

func (q *Queries) GetUserTenants(ctx context.Context, userID uuid.UUID) ([]*GetUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, getUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUserTenantsRow{}
	for rows.Next() {
		var i GetUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SchemaName,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTenant = `-- name: RemoveUserFromTenant :exec
DELETE FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveUserFromTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveUserFromTenant(ctx context.Context, arg *RemoveUserFromTenantParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTenant, arg.TenantID, arg.UserID)
	return err
}

const setDefaultTenant = `-- name: SetDefaultTenant :exec
UPDATE tenant_users
SET is_default = (tenant_id = $2)
WHERE user_id = $1
`

type SetDefaultTenantParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) SetDefaultTenant(ctx context.Context, arg *SetDefaultTenantParams) error {
	_, err := q.db.Exec(ctx, setDefaultTenant, arg.UserID, arg.TenantID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const userHasTenantAccess = `-- name: UserHasTenantAccess :one
SELECT EXISTS(
    SELECT 1 FROM tenant_users
    WHERE tenant_id = $1 AND user_id = $2
)
`

type UserHasTenantAccessParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UserHasTenantAccess(ctx context.Context, arg *UserHasTenantAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasTenantAccess, arg.TenantID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
