version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (github.com/jackc/pgx/v5.Tx).Rollback
        - (*database/sql.Rows).Close
        - (*os.File).Close

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    gosec:
      excludes:
        - G104
        - G304

    misspell:
      locale: US

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: docs/docs.go
        linters:
          - lll
      - path: _test\.go
        linters:
          - funlen
          - dupl
          - errcheck
          - govet
          - staticcheck
      - path: _test\.go
        linters:
          - unparam
      - linters:
          - staticcheck
        text: "SA5011"
    max-issues-per-linter: 50
    max-same-issues: 10

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/openaccounting/openaccounting

  exclusions:
    generated: lax
    paths:
      - docs/docs.go
