package cutover

import (
	"fmt"
	"sort"
	"strings"
)

var providerPresetAliases = map[MigrationProviderPreset]map[FileKind]map[string]string{
	MigrationProviderPresetMerit: {
		KindAccounts: {
			"konto":         "code",
			"konto_kood":    "code",
			"kontokood":     "code",
			"konto_nimi":    "name",
			"kontonimi":     "name",
			"konto_nimetus": "name",
			"konto_tüüp":    "account_type",
			"konto_tyyp":    "account_type",
			"tüüp":          "account_type",
			"tyyp":          "account_type",
			"liik":          "account_type",
		},
		KindContacts: {
			"kood":          "code",
			"kliendi_kood":  "code",
			"kliendikood":   "code",
			"hankija_kood":  "code",
			"hankijakood":   "code",
			"klient":        "name",
			"hankija":       "name",
			"nimi":          "name",
			"registrikood":  "reg_code",
			"registri_kood": "reg_code",
			"reg_nr":        "reg_code",
			"kmkr_nr":       "vat_number",
			"kmkr":          "vat_number",
			"e_post":        "email",
			"epost":         "email",
		},
		KindInvoices: mergeAliases(meritCommercialDocumentAliases("invoice_number", "issue_date"), map[string]string{
			"arve_nr":      "invoice_number",
			"arvenr":       "invoice_number",
			"arve_number":  "invoice_number",
			"arve_kuupäev": "issue_date",
			"arve_kuupaev": "issue_date",
			"arve_tüüp":    "invoice_type",
			"arve_tyyp":    "invoice_type",
			"arve_liik":    "invoice_type",
		}),
		KindQuotes: mergeAliases(meritCommercialDocumentAliases("quote_number", "quote_date"), map[string]string{
			"pakkumise_nr":      "quote_number",
			"pakkumisenr":       "quote_number",
			"pakkumise_kuupäev": "quote_date",
			"pakkumise_kuupaev": "quote_date",
		}),
		KindOrders: mergeAliases(meritCommercialDocumentAliases("order_number", "order_date"), map[string]string{
			"tellimuse_nr":      "order_number",
			"tellimusenr":       "order_number",
			"tellimuse_kuupäev": "order_date",
			"tellimuse_kuupaev": "order_date",
		}),
		KindRecurringInvoices: meritCommercialDocumentAliases("name", "start_date"),
		KindExpenses: {
			"kulu_nr":                "expense_number",
			"kulunr":                 "expense_number",
			"dokumendi_nr":           "expense_number",
			"dokumendinr":            "expense_number",
			"kuupäev":                "expense_date",
			"kuupaev":                "expense_date",
			"kulu_kuupäev":           "expense_date",
			"kulu_kuupaev":           "expense_date",
			"hankija":                "merchant",
			"tarnija":                "merchant",
			"müüja":                  "merchant",
			"myyja":                  "merchant",
			"kaupmees":               "merchant",
			"selgitus":               "description",
			"kirjeldus":              "description",
			"töötaja_id":             "employee_id",
			"tootaja_id":             "employee_id",
			"kontakt_id":             "contact_id",
			"hankija_id":             "contact_id",
			"kontakt_kood":           "contact_code",
			"kliendi_kood":           "contact_code",
			"kliendikood":            "contact_code",
			"hankija_kood":           "contact_code",
			"hankijakood":            "contact_code",
			"hankija_nimi":           "contact_name",
			"hankijanimi":            "contact_name",
			"hankija_registrikood":   "contact_reg_code",
			"hankija_reg_kood":       "contact_reg_code",
			"hankija_kmkr":           "contact_vat_number",
			"hankija_kmkr_nr":        "contact_vat_number",
			"hankija_epost":          "contact_email",
			"hankija_e_post":         "contact_email",
			"kulu_konto_id":          "expense_account_id",
			"kulu_konto":             "expense_account_code",
			"kulu_konto_kood":        "expense_account_code",
			"kulukonto":              "expense_account_code",
			"makse_konto_id":         "payment_account_id",   //nolint:misspell // Estonian CSV header alias.
			"makse_konto":            "payment_account_code", //nolint:misspell // Estonian CSV header alias.
			"makse_konto_kood":       "payment_account_code", //nolint:misspell // Estonian CSV header alias.
			"tasumise_konto":         "payment_account_code",
			"summa":                  "amount",
			"valuuta":                "currency",
			"valuutakurss":           "exchange_rate",
			"valuuta_kurss":          "exchange_rate",
			"vajab_tšekki":           "requires_receipt",
			"vajab_tsekki":           "requires_receipt",
			"tšekk_nõutud":           "requires_receipt",
			"tsekk_noutud":           "requires_receipt",
			"staatus":                "status",
			"esitatud":               "submitted_at",
			"kinnitatud":             "approved_at",
			"tagasi_lükatud":         "rejected_at",
			"tagasi_lykatud":         "rejected_at",
			"tagasilükkamise_põhjus": "rejection_reason",
			"tagasilykkamise_pohjus": "rejection_reason",
		},
		KindPayments: {
			"makse_nr":       "payment_number", //nolint:misspell // Estonian CSV header alias.
			"maksenr":        "payment_number",
			"makse_tüüp":     "payment_type", //nolint:misspell // Estonian CSV header alias.
			"makse_tyyp":     "payment_type", //nolint:misspell // Estonian CSV header alias.
			"kuupäev":        "payment_date",
			"kuupaev":        "payment_date",
			"kontakt_id":     "contact_id",
			"klient_id":      "contact_id",
			"hankija_id":     "contact_id",
			"kontakt_kood":   "contact_code",
			"kliendi_kood":   "contact_code",
			"kliendikood":    "contact_code",
			"hankija_kood":   "contact_code",
			"hankijakood":    "contact_code",
			"kontakt":        "contact_name",
			"klient":         "contact_name",
			"hankija_nimi":   "contact_name",
			"hankijanimi":    "contact_name",
			"registrikood":   "contact_reg_code",
			"registri_kood":  "contact_reg_code",
			"reg_nr":         "contact_reg_code",
			"kmkr":           "contact_vat_number",
			"kmkr_nr":        "contact_vat_number",
			"e_post":         "contact_email",
			"epost":          "contact_email",
			"summa":          "amount",
			"arve_nr":        "invoice_number",
			"arvenr":         "invoice_number",
			"arve_number":    "invoice_number",
			"makseviis":      "payment_method", //nolint:misspell // Estonian CSV header alias.
			"pangakonto":     "bank_account",
			"viitenumber":    "reference",
			"viite_number":   "reference",
			"selgitus":       "notes",
			"kirjeldus":      "notes",
			"jaotuse_summa":  "allocation_amount",
			"jaotatud_summa": "allocation_amount",
		},
		KindBankAccounts: {
			"pangakonto":  "account_number",
			"panga_konto": "account_number",
			"konto_nr":    "account_number",
			"kontonr":     "account_number",
			"pank":        "bank_name",
			"panga_nimi":  "bank_name",
			"konto_nimi":  "name",
			"konto_kood":  "gl_account_code",
			"valuuta":     "currency",
			"vaikimisi":   "is_default",
			"aktiivne":    "is_active",
		},
		KindBankTransactions: {
			"kuupäev":           "date",
			"kuupaev":           "date",
			"summa":             "amount",
			"selgitus":          "description",
			"kirjeldus":         "description",
			"viitenumber":       "reference",
			"viite_number":      "reference",
			"vastaspool":        "counterparty_name",
			"vastaspoole_konto": "counterparty_account",
			"konto":             "source_account",
			"valuuta":           "currency",
		},
		KindCostCenters: {
			"kulukoht":         "code",
			"kulukoha_kood":    "code",
			"kulukoha_nimi":    "name",
			"kulukoha_nimetus": "name",
			"nimetus":          "name",
		},
		KindCostAllocations: {
			"kulukoht":         "cost_center_code",
			"kulukoha_kood":    "cost_center_code",
			"kanne_rea_id":     "journal_entry_line_id",
			"kande_rea_id":     "journal_entry_line_id",
			"summa":            "amount",
			"jaotuse_summa":    "amount",
			"protsent":         "allocation_percentage",
			"jaotuse_protsent": "allocation_percentage",
			"kuupäev":          "allocation_date",
			"kuupaev":          "allocation_date",
			"selgitus":         "notes",
			"kirjeldus":        "notes",
		},
		KindProductCategories: {
			"grupp":             "name",
			"grupi_nimi":        "name",
			"grupp_nimi":        "name",
			"tootegrupp":        "name",
			"toote_grupp":       "name",
			"artiklikategooria": "name",
			"ülemgrupp":         "parent_name",
			"ylemgrupp":         "parent_name",
			"ülema_grupp":       "parent_name",
			"ylema_grupp":       "parent_name",
			"parent_tootegrupp": "parent_name",
			"tootegrupp_parent": "parent_name",
			"tootegrupi_parent": "parent_name",
		},
		KindWarehouses: {
			"ladu":        "code",
			"laokood":     "code",
			"ladu_kood":   "code",
			"ladu_nimi":   "name",
			"laonimi":     "name",
			"asukoht":     "address",
			"aadress":     "address",
			"vaikimisi":   "is_default",
			"aktiivne":    "is_active",
			"aktiivsus":   "is_active",
			"ladu_status": "status",
		},
		KindProducts: {
			"artikkel":             "code",
			"artikli_kood":         "code",
			"toode":                "name",
			"toote_nimi":           "name",
			"nimetus":              "name",
			"tootegrupp":           "category_name",
			"toote_grupp":          "category_name",
			"grupp":                "category_name",
			"müügihind":            "sales_price",
			"myygihind":            "sales_price",
			"ostuhind":             "purchase_price",
			"käibemaks":            "vat_rate",
			"kaibemaks":            "vat_rate",
			"hankija":              "supplier_code",
			"hankija_kood":         "supplier_code",
			"hankijakood":          "supplier_code",
			"hankija_nimi":         "supplier_name",
			"hankijanimi":          "supplier_name",
			"tarnija_nimi":         "supplier_name",
			"tarnijanimi":          "supplier_name",
			"hankija_registrikood": "supplier_reg_code",
			"hankija_reg_kood":     "supplier_reg_code",
			"hankija_kmkr":         "supplier_vat_number",
			"hankija_kmkr_nr":      "supplier_vat_number",
			"hankija_epost":        "supplier_email",
			"hankija_e_post":       "supplier_email",
		},
		KindStockAdjustments: {
			"artikkel":        "product_code",
			"artikli_kood":    "product_code",
			"toode":           "product_code",
			"ladu":            "warehouse_code",
			"ladu_kood":       "warehouse_code",
			"laokood":         "warehouse_code",
			"kogus":           "quantity",
			"jääk":            "quantity",
			"jaak":            "quantity",
			"laoseis":         "quantity",
			"omahind":         "unit_cost",
			"soetushind":      "unit_cost",
			"partii":          "lot_number",
			"partii_nr":       "lot_number",
			"partiinumber":    "lot_number",
			"seerianumber":    "serial_number",
			"seeria_nr":       "serial_number",
			"aegumiskuupäev":  "expiry_date",
			"aegumiskuupaev":  "expiry_date",
			"säilivuskuupäev": "expiry_date",
			"sailivuskuupaev": "expiry_date",
			"selgitus":        "reason",
			"kirjeldus":       "reason",
		},
		KindFixedAssets: {
			"põhivara_nr":                     "asset_number",
			"pohivara_nr":                     "asset_number",
			"põhivaranr":                      "asset_number",
			"pohivaranr":                      "asset_number",
			"põhivara":                        "name",
			"pohivara":                        "name",
			"nimetus":                         "name",
			"soetuskuupäev":                   "purchase_date",
			"soetuskuupaev":                   "purchase_date",
			"soetusmaksumus":                  "purchase_cost",
			"soetus_summa":                    "purchase_cost",
			"seerianumber":                    "serial_number",
			"asukoht":                         "location",
			"kulumi_meetod":                   "depreciation_method",
			"amortisatsiooni_meetod":          "depreciation_method",
			"kasulik_elu_kuud":                "useful_life_months",
			"kasutusiga_kuud":                 "useful_life_months",
			"jääkväärtus":                     "residual_value",
			"jaakvaartus":                     "residual_value",
			"akumuleeritud_kulum":             "accumulated_depreciation",
			"kogunenud_kulum":                 "accumulated_depreciation",
			"jääkmaksumus":                    "book_value",
			"jaakmaksumus":                    "book_value",
			"vara_konto":                      "asset_account_code",
			"põhivara_konto":                  "asset_account_code",
			"pohivara_konto":                  "asset_account_code",
			"kulumi_konto":                    "depreciation_expense_account_code",
			"akumuleeritud_kulumi_konto":      "accumulated_depreciation_account_code",
			"akumuleeritud_kulum_konto":       "accumulated_depreciation_account_code",
			"akumuleeritud_kulumi_konto_kood": "accumulated_depreciation_account_code",
			"akumuleeritud_kulum_konto_kood":  "accumulated_depreciation_account_code",
			"hankija":                         "supplier_code",
			"hankija_kood":                    "supplier_code",
			"hankijakood":                     "supplier_code",
			"hankija_nimi":                    "supplier_name",
			"hankijanimi":                     "supplier_name",
			"tarnija_nimi":                    "supplier_name",
			"tarnijanimi":                     "supplier_name",
			"hankija_registrikood":            "supplier_reg_code",
			"hankija_reg_kood":                "supplier_reg_code",
			"hankija_kmkr":                    "supplier_vat_number",
			"hankija_kmkr_nr":                 "supplier_vat_number",
			"hankija_epost":                   "supplier_email",
			"hankija_e_post":                  "supplier_email",
		},
		KindOpeningBalances: {
			"konto":     "account_code",
			"deebet":    "debit",
			"kreedit":   "credit",
			"kulukoht":  "cost_center_code",
			"projekt":   "project_code",
			"kirjeldus": "description",
			"selgitus":  "description",
		},
		KindJournalEntries: {
			"kanne_nr":      "entry_reference",
			"kandenr":       "entry_reference",
			"dokumendi_nr":  "entry_reference",
			"dokumendinr":   "entry_reference",
			"kanne_rea_id":  "line_id",
			"kande_rea_id":  "line_id",
			"kuupäev":       "entry_date",
			"kuupaev":       "entry_date",
			"konto":         "account_code",
			"deebet":        "debit",
			"kreedit":       "credit",
			"selgitus":      "line_description",
			"kirjeldus":     "line_description",
			"valuuta":       "currency",
			"valuutakurss":  "exchange_rate",
			"valuuta_kurss": "exchange_rate",
		},
		KindEmployees: {
			"importcode":          "employee_number",
			"import_code":         "employee_number",
			"contractcode":        "employee_number",
			"contract_code":       "employee_number",
			"contractno":          "employee_number",
			"contract_no":         "employee_number",
			"personalcode":        "personal_code",
			"personal_code":       "personal_code",
			"firstname":           "first_name",
			"first_name":          "first_name",
			"surname":             "last_name",
			"sur_name":            "last_name",
			"bankaccountno":       "bank_account",
			"bank_account_no":     "bank_account",
			"phoneno":             "phone",
			"phone_no":            "phone",
			"startdate":           "start_date",
			"start_date":          "start_date",
			"enddate":             "end_date",
			"end_date":            "end_date",
			"amount":              "base_salary",
			"salarytypeimpcode":   "salary_type_import_code",
			"salary_type_impcode": "salary_type_import_code",
			"departmentcode":      "department",
			"department_code":     "department",
		},
		KindPayrollHistory: meritPayrollHistoryAliases("gross_salary"),
		KindLeaveBalances: {
			"contractcode":     "employee_number",
			"contract_code":    "employee_number",
			"personalcode":     "personal_code",
			"personal_code":    "personal_code",
			"date":             "balance_date",
			"balancedate":      "balance_date",
			"balance_date":     "balance_date",
			"typecode":         "absence_type_code",
			"type_code":        "absence_type_code",
			"days":             "entitled_days",
			"daysobligations":  "entitled_days",
			"days_obligations": "entitled_days",
			"initbalance":      "carryover_days",
			"init_balance":     "carryover_days",
			"daysunused":       "carryover_days",
			"days_unused":      "carryover_days",
			"daysacquired":     "used_days",
			"days_acquired":    "used_days",
		},
		KindTSDHistory: meritPayrollHistoryAliases("gross_payment"),
		KindKMDHistory: {
			"aasta":                "year",
			"perioodi_aasta":       "year",
			"kuu":                  "month",
			"perioodi_kuu":         "month",
			"deklaratsiooni_kuu":   "month",
			"deklaratsiooni_aasta": "year",
			"staatus":              "status",
			"deklaratsiooni_olek":  "status",
			"esitatud":             "submitted_at",
			"esitamise_kuupäev":    "submitted_at",
			"esitamise_kuupaev":    "submitted_at",
			"rea_kood":             "row_code",
			"rida":                 "row_code",
			"rea_nr":               "row_code",
			"rea_nimetus":          "description",
			"kirjeldus":            "description",
			"maksustatav_summa":    "tax_base",
			"maksustatav_kaive":    "tax_base",
			"käibemaks":            "tax_amount",
			"kaibemaks":            "tax_amount",
			"km_summa":             "tax_amount",
			"väljundkäibemaks":     "total_output_vat",
			"valjundkaibemaks":     "total_output_vat",
			"sisendkäibemaks":      "total_input_vat",
			"sisendkaibemaks":      "total_input_vat",
		},
	},
	MigrationProviderPresetSmartAccounts: {
		KindAccounts: {
			"account_no":          "code",
			"account_number":      "code",
			"account_title":       "name",
			"account_description": "name",
			"classification":      "account_type",
			"parent_account":      "parent_code",
			"parent_account_no":   "parent_code",
		},
		KindContacts: {
			"client_no":       "code",
			"client_number":   "code",
			"client_name":     "name",
			"customer_no":     "code",
			"customer_number": "code",
			"vendor_no":       "code",
			"vendor_number":   "code",
			"vendor_name":     "name",
			"supplier_no":     "code",
			"supplier_number": "code",
			"registration_no": "reg_code",
			"registry_no":     "reg_code",
			"vat_no":          "vat_number",
			"email_address":   "email",
		},
		KindInvoices:          smartAccountsCommercialDocumentAliases("invoice_number", "issue_date"),
		KindQuotes:            smartAccountsCommercialDocumentAliases("quote_number", "quote_date"),
		KindOrders:            smartAccountsCommercialDocumentAliases("order_number", "order_date"),
		KindRecurringInvoices: smartAccountsCommercialDocumentAliases("name", "start_date"),
		KindExpenses: {
			"expense_no":            "expense_number",
			"expense_number":        "expense_number",
			"document_no":           "expense_number",
			"document_number":       "expense_number",
			"posting_date":          "expense_date",
			"expense_date":          "expense_date",
			"document_date":         "expense_date",
			"vendor_name":           "merchant",
			"supplier_name":         "merchant",
			"merchant_name":         "merchant",
			"description":           "description",
			"memo":                  "description",
			"line_memo":             "description",
			"employee_id":           "employee_id",
			"contact_id":            "contact_id",
			"vendor_id":             "contact_id",
			"supplier_id":           "contact_id",
			"contact_no":            "contact_code",
			"contact_number":        "contact_code",
			"vendor_no":             "contact_code",
			"vendor_number":         "contact_code",
			"vendor_code":           "contact_code",
			"supplier_no":           "contact_code",
			"supplier_number":       "contact_code",
			"supplier_code":         "contact_code",
			"contact_name":          "contact_name",
			"vendor_contact_name":   "contact_name",
			"supplier_contact_name": "contact_name",
			"contact_reg_no":        "contact_reg_code",
			"vendor_reg_no":         "contact_reg_code",
			"supplier_reg_no":       "contact_reg_code",
			"contact_vat_no":        "contact_vat_number",
			"vendor_vat_no":         "contact_vat_number",
			"supplier_vat_no":       "contact_vat_number",
			"contact_email":         "contact_email",
			"vendor_email":          "contact_email",
			"supplier_email":        "contact_email",
			"expense_account_no":    "expense_account_code",
			"expense_account_code":  "expense_account_code",
			"expense_account_id":    "expense_account_id",
			"payment_account_no":    "payment_account_code",
			"payment_account_code":  "payment_account_code",
			"payment_account_id":    "payment_account_id",
			"paid_from_account_no":  "payment_account_code",
			"amount":                "amount",
			"expense_amount":        "amount",
			"currency_code":         "currency",
			"exchange_rate":         "exchange_rate",
			"receipt_required":      "requires_receipt",
			"requires_receipt":      "requires_receipt",
			"expense_status":        "status",
			"submitted_date":        "submitted_at",
			"approved_date":         "approved_at",
			"rejected_date":         "rejected_at",
			"rejection_note":        "rejection_reason",
		},
		KindPayments: {
			"payment_no":            "payment_number",
			"payment_number":        "payment_number",
			"payment_date":          "payment_date",
			"payment_kind":          "payment_type",
			"contact_id":            "contact_id",
			"customer_id":           "contact_id",
			"supplier_id":           "contact_id",
			"contact_no":            "contact_code",
			"contact_number":        "contact_code",
			"customer_no":           "contact_code",
			"customer_number":       "contact_code",
			"vendor_no":             "contact_code",
			"vendor_number":         "contact_code",
			"supplier_no":           "contact_code",
			"supplier_number":       "contact_code",
			"contact_name":          "contact_name",
			"customer_name":         "contact_name",
			"supplier_contact_name": "contact_name",
			"contact_reg_no":        "contact_reg_code",
			"customer_reg_no":       "contact_reg_code",
			"supplier_reg_no":       "contact_reg_code",
			"contact_vat_no":        "contact_vat_number",
			"customer_vat_no":       "contact_vat_number",
			"supplier_vat_no":       "contact_vat_number",
			"contact_email":         "contact_email",
			"customer_email":        "contact_email",
			"supplier_email":        "contact_email",
			"paid_amount":           "amount",
			"document_no":           "invoice_number",
			"document_number":       "invoice_number",
			"invoice_no":            "invoice_number",
			"payment_method":        "payment_method",
			"bank_account_no":       "bank_account",
			"reference_no":          "reference",
			"payment_reference":     "reference",
			"payment_memo":          "notes",
			"line_memo":             "notes",
			"allocated_amount":      "allocation_amount",
		},
		KindBankAccounts: {
			"bank_account_no":      "account_number",
			"bank_account_name":    "name",
			"account_no":           "account_number",
			"bank_name":            "bank_name",
			"currency_code":        "currency",
			"cash_account_no":      "gl_account_code",
			"ledger_account_no":    "gl_account_code",
			"default_bank_account": "is_default",
			"active":               "is_active",
		},
		KindBankTransactions: {
			"transaction_date":        "date",
			"booking_date":            "date",
			"transaction_sum":         "amount",
			"currency_code":           "currency",
			"transaction_text":        "description",
			"transaction_memo":        "description",
			"account_no":              "source_account",
			"bank_account_no":         "source_account",
			"transaction_reference":   "reference",
			"reference_no":            "reference",
			"counterparty_name":       "counterparty_name",
			"counterparty_account_no": "counterparty_account",
			"counterparty_iban":       "counterparty_account",
			"external_id":             "external_id",
			"archive_id":              "external_id",
		},
		KindCostCenters: {
			"cost_center_no":     "code",
			"cost_center_number": "code",
			"department_no":      "code",
			"department_number":  "code",
			"cost_center_title":  "name",
			"department_name":    "name",
			"parent_center_no":   "parent_code",
			"parent_department":  "parent_code",
		},
		KindCostAllocations: {
			"cost_center_no":          "cost_center_code",
			"cost_center_number":      "cost_center_code",
			"department_no":           "cost_center_code",
			"department_number":       "cost_center_code",
			"journal_line_id":         "journal_entry_line_id",
			"entry_line_id":           "journal_entry_line_id",
			"transaction_line_id":     "journal_entry_line_id",
			"allocated_amount":        "amount",
			"amount_allocated":        "amount",
			"allocation_amount":       "amount",
			"allocated_percent":       "allocation_percentage",
			"allocation_percent":      "allocation_percentage",
			"allocation_percentage":   "allocation_percentage",
			"posting_date":            "allocation_date",
			"transaction_date":        "allocation_date",
			"allocation_date":         "allocation_date",
			"line_memo":               "notes",
			"transaction_memo":        "notes",
			"cost_allocation_comment": "notes",
		},
		KindProductCategories: {
			"item_group":           "name",
			"item_group_name":      "name",
			"product_group":        "name",
			"product_group_name":   "name",
			"parent_group":         "parent_name",
			"parent_item_group":    "parent_name",
			"parent_product_group": "parent_name",
		},
		KindWarehouses: {
			"warehouse_no":      "code",
			"warehouse_number":  "code",
			"location_no":       "code",
			"location_number":   "code",
			"location_name":     "name",
			"site_name":         "name",
			"site_address":      "address",
			"default_warehouse": "is_default",
		},
		KindProducts: {
			"item_no":              "code",
			"item_number":          "code",
			"item_name":            "name",
			"item_type":            "product_type",
			"item_group":           "category_name",
			"item_group_name":      "category_name",
			"product_group":        "category_name",
			"product_group_name":   "category_name",
			"sales_price":          "sales_price",
			"purchase_price":       "purchase_price",
			"vat_percent":          "vat_rate",
			"supplier_no":          "supplier_code",
			"supplier_number":      "supplier_code",
			"supplier_code":        "supplier_code",
			"vendor_no":            "supplier_code",
			"vendor_number":        "supplier_code",
			"vendor_code":          "supplier_code",
			"supplier_name":        "supplier_name",
			"vendor_name":          "supplier_name",
			"supplier_reg_no":      "supplier_reg_code",
			"supplier_registry_no": "supplier_reg_code",
			"vendor_reg_no":        "supplier_reg_code",
			"supplier_vat_no":      "supplier_vat_number",
			"vendor_vat_no":        "supplier_vat_number",
			"supplier_email":       "supplier_email",
			"vendor_email":         "supplier_email",
		},
		KindStockAdjustments: {
			"item_no":          "product_code",
			"item_number":      "product_code",
			"warehouse_no":     "warehouse_code",
			"warehouse_number": "warehouse_code",
			"location_no":      "warehouse_code",
			"location_number":  "warehouse_code",
			"balance_qty":      "quantity",
			"quantity_on_hand": "quantity",
			"stock_qty":        "quantity",
			"stock_quantity":   "quantity",
			"average_cost":     "unit_cost",
			"avg_cost":         "unit_cost",
			"batch_no":         "lot_number",
			"batch_number":     "lot_number",
			"serial_no":        "serial_number",
			"best_before":      "expiry_date",
			"expiry":           "expiry_date",
		},
		KindFixedAssets: {
			"fixed_asset_no":                      "asset_number",
			"fixed_asset_number":                  "asset_number",
			"asset_description":                   "name",
			"asset_group":                         "category_name",
			"asset_group_name":                    "category_name",
			"purchase_value":                      "purchase_cost",
			"acquisition_value":                   "purchase_cost",
			"depreciation_months":                 "useful_life_months",
			"fixed_asset_account_no":              "asset_account_code",
			"fixed_asset_account":                 "asset_account_code",
			"depreciation_expense_account_no":     "depreciation_expense_account_code",
			"accumulated_depreciation_account_no": "accumulated_depreciation_account_code",
			"supplier_no":                         "supplier_code",
			"supplier_number":                     "supplier_code",
			"supplier_code":                       "supplier_code",
			"vendor_no":                           "supplier_code",
			"vendor_number":                       "supplier_code",
			"vendor_code":                         "supplier_code",
			"supplier_name":                       "supplier_name",
			"vendor_name":                         "supplier_name",
			"supplier_reg_no":                     "supplier_reg_code",
			"supplier_registry_no":                "supplier_reg_code",
			"vendor_reg_no":                       "supplier_reg_code",
			"supplier_vat_no":                     "supplier_vat_number",
			"vendor_vat_no":                       "supplier_vat_number",
			"supplier_email":                      "supplier_email",
			"vendor_email":                        "supplier_email",
		},
		KindOpeningBalances: {
			"account_no":     "account_code",
			"account_number": "account_code",
			"debit_amount":   "debit",
			"credit_amount":  "credit",
			"line_memo":      "description",
		},
		KindJournalEntries: {
			"entry_no":            "entry_reference",
			"entry_number":        "entry_reference",
			"transaction_no":      "entry_reference",
			"journal_line_id":     "line_id",
			"entry_line_id":       "line_id",
			"transaction_line_id": "line_id",
			"transaction_date":    "entry_date",
			"account_no":          "account_code",
			"account_number":      "account_code",
			"debit_amount":        "debit",
			"credit_amount":       "credit",
			"currency_code":       "currency",
			"line_memo":           "line_description",
			"transaction_memo":    "entry_description",
		},
		KindEmployees: {
			"employee_no":     "employee_number",
			"employee_number": "employee_number",
			"personal_no":     "personal_code",
			"personal_code":   "personal_code",
			"firstname":       "first_name",
			"first_name":      "first_name",
			"surname":         "last_name",
			"last_name":       "last_name",
			"bank_account_no": "bank_account",
			"start_date":      "start_date",
			"end_date":        "end_date",
			"salary_amount":   "base_salary",
		},
		KindPayrollHistory: {
			"employee_no":       "employee_number",
			"employee_number":   "employee_number",
			"personal_no":       "personal_code",
			"personal_code":     "personal_code",
			"employee_name":     "name",
			"period":            "period_code",
			"period_code":       "period_code",
			"accounting_period": "period_code",
			"gross_amount":      "gross_salary",
			"salary_amount":     "gross_salary",
			"net_amount":        "net_salary",
			"employer_cost":     "total_employer_cost",
			"social_tax_amount": "social_tax",
			"income_tax_amount": "income_tax",
		},
		KindLeaveBalances: {
			"employee_no":      "employee_number",
			"employee_number":  "employee_number",
			"personal_no":      "personal_code",
			"personal_code":    "personal_code",
			"balance_date":     "balance_date",
			"leave_type_code":  "absence_type_code",
			"leave_type":       "absence_type",
			"entitlement_days": "entitled_days",
			"unused_days":      "carryover_days",
			"used_days":        "used_days",
		},
		KindTSDHistory: {
			"employee_no":       "employee_number",
			"employee_number":   "employee_number",
			"personal_no":       "personal_code",
			"personal_code":     "personal_code",
			"employee_name":     "name",
			"period":            "period_code",
			"period_code":       "period_code",
			"accounting_period": "period_code",
			"gross_amount":      "gross_payment",
			"salary_amount":     "gross_payment",
			"income_tax_amount": "income_tax",
			"social_tax_amount": "social_tax",
		},
		KindKMDHistory: {
			"vat_return_year":      "year",
			"vat_period_year":      "year",
			"tax_return_year":      "year",
			"vat_return_month":     "month",
			"vat_period_month":     "month",
			"tax_return_month":     "month",
			"vat_return_status":    "status",
			"tax_return_status":    "status",
			"filing_status":        "status",
			"filing_date":          "submitted_at",
			"submitted_date":       "submitted_at",
			"vat_row":              "row_code",
			"vat_row_code":         "row_code",
			"line_no":              "row_code",
			"line_number":          "row_code",
			"line_description":     "description",
			"vat_line_description": "description",
			"vat_base":             "tax_base",
			"taxable_value":        "tax_base",
			"vat_sum":              "tax_amount",
			"vat_amount":           "tax_amount",
			"output_tax":           "total_output_vat",
			"output_vat_total":     "total_output_vat",
			"input_tax":            "total_input_vat",
			"input_vat_total":      "total_input_vat",
		},
	},
	MigrationProviderPresetDirecto: directoProviderPresetAliases(),
}

func normalizeMigrationProviderPreset(preset MigrationProviderPreset) (MigrationProviderPreset, error) {
	switch normalized := normalizedHeader(string(preset)); normalized {
	case "":
		return MigrationProviderPresetGeneric, nil
	case string(MigrationProviderPresetGeneric):
		return MigrationProviderPresetGeneric, nil
	case string(MigrationProviderPresetMerit):
		return MigrationProviderPresetMerit, nil
	case string(MigrationProviderPresetSmartAccounts), "smart_accounts", "smart_account":
		return MigrationProviderPresetSmartAccounts, nil
	case string(MigrationProviderPresetDirecto), "directo_erp":
		return MigrationProviderPresetDirecto, nil
	default:
		return "", fmt.Errorf("unsupported provider_preset %q (expected generic, merit, smartaccounts, or directo)", preset)
	}
}

func fileSpecForProviderPreset(kind FileKind, preset MigrationProviderPreset) fileSpec {
	spec := fileSpecs[kind]
	if preset == MigrationProviderPresetGeneric {
		return spec
	}
	aliases := providerPresetAliases[preset][kind]
	if len(aliases) == 0 {
		return spec
	}
	spec.aliases = mergeAliases(spec.aliases, aliases)
	return spec
}

func ListMigrationProviderPresets() []MigrationProviderPresetInfo {
	presets := []MigrationProviderPreset{
		MigrationProviderPresetGeneric,
		MigrationProviderPresetMerit,
		MigrationProviderPresetSmartAccounts,
		MigrationProviderPresetDirecto,
	}
	infos := make([]MigrationProviderPresetInfo, 0, len(presets))
	for _, preset := range presets {
		infos = append(infos, buildMigrationProviderPresetInfo(preset))
	}
	return infos
}

func buildMigrationProviderPresetInfo(preset MigrationProviderPreset) MigrationProviderPresetInfo {
	info := MigrationProviderPresetInfo{
		Preset:      preset,
		Label:       migrationProviderPresetLabel(preset),
		Description: migrationProviderPresetDescription(preset),
	}
	for _, kind := range migrationPresetCatalogFileKinds() {
		spec, ok := fileSpecs[kind]
		if !ok {
			continue
		}
		presetAliases := providerPresetAliases[preset][kind]
		kindInfo := MigrationProviderPresetKindInfo{
			Kind:                 kind,
			RequiredColumnGroups: cloneRequiredColumnGroups(spec.requiredGroups),
			PresetAliasCount:     len(presetAliases),
			SampleAliases:        sampleProviderPresetAliases(presetAliases, 5),
		}
		info.FileKinds = append(info.FileKinds, kindInfo)
		info.PresetAliasCount += kindInfo.PresetAliasCount
	}
	info.FileKindCount = len(info.FileKinds)
	return info
}

func migrationProviderPresetLabel(preset MigrationProviderPreset) string {
	switch preset {
	case MigrationProviderPresetMerit:
		return "Merit"
	case MigrationProviderPresetSmartAccounts:
		return "SmartAccounts"
	case MigrationProviderPresetDirecto:
		return "Directo"
	default:
		return "Generic"
	}
}

func migrationProviderPresetDescription(preset MigrationProviderPreset) string {
	switch preset {
	case MigrationProviderPresetMerit:
		return "Adds Merit Aktiva and Merit Palk CSV header aliases before canonical cutover validation."
	case MigrationProviderPresetSmartAccounts:
		return "Adds SmartAccounts CSV export header aliases before canonical cutover validation."
	case MigrationProviderPresetDirecto:
		return "Adds Directo mass-import and XML Direct-style CSV header aliases before canonical cutover validation."
	default:
		return "Uses Open Accounting canonical cutover headers without vendor-specific alias expansion."
	}
}

func directoProviderPresetAliases() map[FileKind]map[string]string {
	return map[FileKind]map[string]string{
		KindAccounts: {
			"konto":         "code",
			"konto_kood":    "code",
			"kontokood":     "code",
			"konto_nimi":    "name",
			"kontonimi":     "name",
			"konto_nimetus": "name",
			"kirjeldus":     "name",
			"konto_tüüp":    "account_type",
			"konto_tyyp":    "account_type",
			"tüüp":          "account_type",
			"tyyp":          "account_type",
			"klass":         "account_type",
			"ülemkonto":     "parent_code",
			"ylemkonto":     "parent_code",
			"parent_konto":  "parent_code",
		},
		KindContacts: {
			"kood":          "code",
			"kliendikood":   "code",
			"kliendi_kood":  "code",
			"hankijakood":   "code",
			"hankija_kood":  "code",
			"klient":        "name",
			"hankija":       "name",
			"nimi":          "name",
			"ärinimi":       "name",
			"arinimi":       "name",
			"registrikood":  "reg_code",
			"registri_kood": "reg_code",
			"reg_kood":      "reg_code",
			"kmkr":          "vat_number",
			"kmkr_nr":       "vat_number",
			"e_post":        "email",
			"epost":         "email",
			"telefon":       "phone",
			"aadress":       "address_line1",
			"riik":          "country_code",
		},
		KindInvoices: mergeAliases(directoCommercialDocumentAliases("invoice_number", "issue_date"), map[string]string{
			"arve":         "invoice_number",
			"arve_nr":      "invoice_number",
			"arvenr":       "invoice_number",
			"arve_number":  "invoice_number",
			"arve_kuupäev": "issue_date",
			"arve_kuupaev": "issue_date",
			"maksetähtaeg": "due_date",
			"maksetahtaeg": "due_date",
			"tähtaeg":      "due_date",
			"tahtaeg":      "due_date",
			"arve_tüüp":    "invoice_type",
			"arve_tyyp":    "invoice_type",
			"arve_liik":    "invoice_type",
		}),
		KindQuotes: mergeAliases(directoCommercialDocumentAliases("quote_number", "quote_date"), map[string]string{
			"pakkumine":         "quote_number",
			"pakkumise_nr":      "quote_number",
			"pakkumisenr":       "quote_number",
			"pakkumise_kuupäev": "quote_date",
			"pakkumise_kuupaev": "quote_date",
		}),
		KindOrders: mergeAliases(directoCommercialDocumentAliases("order_number", "order_date"), map[string]string{
			"tellimus":          "order_number",
			"tellimuse_nr":      "order_number",
			"tellimusenr":       "order_number",
			"tellimuse_kuupäev": "order_date",
			"tellimuse_kuupaev": "order_date",
			"kliendi_tellimus":  "customer_order_number",
		}),
		KindRecurringInvoices: mergeAliases(directoCommercialDocumentAliases("name", "start_date"), map[string]string{
			"leping":       "name",
			"lepingu_nr":   "name",
			"algus":        "start_date",
			"alguskuupäev": "start_date",
			"alguskuupaev": "start_date",
			"lõpp":         "end_date",
			"lopp":         "end_date",
		}),
		KindExpenses: {
			"kulutus":                "expense_number",
			"kulutuse_nr":            "expense_number",
			"dokumendi_nr":           "expense_number",
			"dokumendinr":            "expense_number",
			"aeg":                    "expense_date",
			"kuupäev":                "expense_date",
			"kuupaev":                "expense_date",
			"hankija":                "merchant",
			"tarnija":                "merchant",
			"müüja":                  "merchant",
			"myyja":                  "merchant",
			"sisu":                   "description",
			"selgitus":               "description",
			"kirjeldus":              "description",
			"töötaja":                "employee_id",
			"tootaja":                "employee_id",
			"kontakt":                "contact_id",
			"hankija_id":             "contact_id",
			"kontakt_kood":           "contact_code",
			"kliendi_kood":           "contact_code",
			"kliendikood":            "contact_code",
			"hankija_kood":           "contact_code",
			"hankijakood":            "contact_code",
			"hankija_nimi":           "contact_name",
			"hankijanimi":            "contact_name",
			"hankija_registrikood":   "contact_reg_code",
			"hankija_reg_kood":       "contact_reg_code",
			"hankija_kmkr":           "contact_vat_number",
			"hankija_kmkr_nr":        "contact_vat_number",
			"hankija_epost":          "contact_email",
			"hankija_e_post":         "contact_email",
			"kulu_konto":             "expense_account_code",
			"kulu_konto_kood":        "expense_account_code",
			"kulukonto":              "expense_account_code",
			"tasumise_konto":         "payment_account_code",
			"makse_konto":            "payment_account_code", //nolint:misspell // Estonian CSV header alias.
			"makse_konto_kood":       "payment_account_code", //nolint:misspell // Estonian CSV header alias.
			"summa":                  "amount",
			"valuuta":                "currency",
			"valuutakurss":           "exchange_rate",
			"valuuta_kurss":          "exchange_rate",
			"tšekk":                  "requires_receipt",
			"tsekk":                  "requires_receipt",
			"tšekk_nõutud":           "requires_receipt",
			"tsekk_noutud":           "requires_receipt",
			"staatus":                "status",
			"esitatud":               "submitted_at",
			"kinnitatud":             "approved_at",
			"tagasi_lükatud":         "rejected_at",
			"tagasi_lykatud":         "rejected_at",
			"tagasilükkamise_põhjus": "rejection_reason",
			"tagasilykkamise_pohjus": "rejection_reason",
		},
		KindPayments: {
			"laekumine":      "payment_number",
			"tasumine":       "payment_number",
			"makse_nr":       "payment_number", //nolint:misspell // Estonian CSV header alias.
			"number":         "payment_number",
			"liik":           "payment_type",
			"makse_tüüp":     "payment_type", //nolint:misspell // Estonian CSV header alias.
			"makse_tyyp":     "payment_type", //nolint:misspell // Estonian CSV header alias.
			"aeg":            "payment_date",
			"kuupäev":        "payment_date",
			"kuupaev":        "payment_date",
			"kontakt":        "contact_id",
			"kontakt_id":     "contact_id",
			"klient_id":      "contact_id",
			"hankija_id":     "contact_id",
			"kontakt_kood":   "contact_code",
			"kliendi_kood":   "contact_code",
			"kliendikood":    "contact_code",
			"hankija_kood":   "contact_code",
			"hankijakood":    "contact_code",
			"klient":         "contact_name",
			"hankija_nimi":   "contact_name",
			"hankijanimi":    "contact_name",
			"registrikood":   "contact_reg_code",
			"registri_kood":  "contact_reg_code",
			"reg_kood":       "contact_reg_code",
			"kmkr":           "contact_vat_number",
			"kmkr_nr":        "contact_vat_number",
			"e_post":         "contact_email",
			"epost":          "contact_email",
			"summa":          "amount",
			"arve":           "invoice_number",
			"arve_nr":        "invoice_number",
			"arvenr":         "invoice_number",
			"viitenr":        "reference",
			"viitenumber":    "reference",
			"selgitus":       "notes",
			"kirjeldus":      "notes",
			"makseviis":      "payment_method",
			"pangakonto":     "bank_account",
			"panga_konto":    "bank_account",
			"jaotatud_summa": "allocation_amount",
			"jaotuse_summa":  "allocation_amount",
		},
		KindBankAccounts: {
			"pangakonto":          "account_number",
			"panga_konto":         "account_number",
			"konto_nr":            "account_number",
			"kontonr":             "account_number",
			"iban":                "account_number",
			"pank":                "bank_name",
			"nimi":                "name",
			"konto_nimi":          "name",
			"raamatupidamiskonto": "gl_account_code",
			"konto_kood":          "gl_account_code",
			"valuuta":             "currency",
			"vaikimisi":           "is_default",
			"aktiivne":            "is_active",
		},
		KindBankTransactions: {
			"aeg":               "date",
			"kuupäev":           "date",
			"kuupaev":           "date",
			"summa":             "amount",
			"valuuta":           "currency",
			"konto":             "source_account",
			"pangakonto":        "source_account",
			"panga_konto":       "source_account",
			"sisu":              "description",
			"selgitus":          "description",
			"kirjeldus":         "description",
			"viitenr":           "reference",
			"viitenumber":       "reference",
			"dok_nr":            "external_id",
			"vastaspool":        "counterparty_name",
			"vastaspoole_konto": "counterparty_account",
			"partneri_konto":    "counterparty_account",
		},
		KindCostCenters: {
			"objekt":        "code",
			"objekti_kood":  "code",
			"objektikood":   "code",
			"kulukoht":      "code",
			"kood":          "code",
			"nimi":          "name",
			"nimetus":       "name",
			"ülemobjekt":    "parent_code",
			"ylemobjekt":    "parent_code",
			"parent_objekt": "parent_code",
		},
		KindCostAllocations: {
			"objekt":           "cost_center_code",
			"kulukoht":         "cost_center_code",
			"objekti_kood":     "cost_center_code",
			"kanne_rea_id":     "journal_entry_line_id",
			"kande_rea_id":     "journal_entry_line_id",
			"rea_id":           "journal_entry_line_id",
			"summa":            "amount",
			"jaotuse_summa":    "amount",
			"protsent":         "allocation_percentage",
			"jaotuse_protsent": "allocation_percentage",
			"aeg":              "allocation_date",
			"kuupäev":          "allocation_date",
			"kuupaev":          "allocation_date",
			"selgitus":         "notes",
			"kirjeldus":        "notes",
		},
		KindProductCategories: {
			"klass":         "name",
			"artikliklass":  "name",
			"artikli_klass": "name",
			"grupp":         "name",
			"tootegrupp":    "name",
			"ülemklass":     "parent_name",
			"ylemklass":     "parent_name",
			"ülemgrupp":     "parent_name",
			"ylemgrupp":     "parent_name",
			"parent_klass":  "parent_name",
			"parent_grupp":  "parent_name",
		},
		KindWarehouses: {
			"ladu":      "code",
			"laokood":   "code",
			"ladu_kood": "code",
			"kood":      "code",
			"nimi":      "name",
			"ladu_nimi": "name",
			"aadress":   "address",
			"asukoht":   "address",
			"vaikimisi": "is_default",
			"aktiivne":  "is_active",
		},
		KindProducts: {
			"artikkel":             "code",
			"artikli_kood":         "code",
			"artiklikood":          "code",
			"kood":                 "code",
			"nimetus":              "name",
			"nimi":                 "name",
			"toode":                "name",
			"klass":                "category_name",
			"artikliklass":         "category_name",
			"grupp":                "category_name",
			"müügihind":            "sales_price",
			"myygihind":            "sales_price",
			"ostuhind":             "purchase_price",
			"omahind":              "purchase_price",
			"käibemaks":            "vat_rate",
			"kaibemaks":            "vat_rate",
			"kmkood":               "vat_rate",
			"müügi_konto":          "sales_account_code",
			"myygi_konto":          "sales_account_code",
			"ostu_konto":           "purchase_account_code",
			"lao_konto":            "inventory_account_code",
			"hankija":              "supplier_code",
			"hankija_kood":         "supplier_code",
			"hankijakood":          "supplier_code",
			"hankija_nimi":         "supplier_name",
			"hankijanimi":          "supplier_name",
			"tarnija_nimi":         "supplier_name",
			"tarnijanimi":          "supplier_name",
			"hankija_registrikood": "supplier_reg_code",
			"hankija_reg_kood":     "supplier_reg_code",
			"hankija_kmkr":         "supplier_vat_number",
			"hankija_kmkr_nr":      "supplier_vat_number",
			"hankija_epost":        "supplier_email",
			"hankija_e_post":       "supplier_email",
		},
		KindStockAdjustments: {
			"artikkel":       "product_code",
			"artikli_kood":   "product_code",
			"artiklikood":    "product_code",
			"ladu":           "warehouse_code",
			"ladu_kood":      "warehouse_code",
			"laokood":        "warehouse_code",
			"kogus":          "quantity",
			"jääk":           "quantity",
			"jaak":           "quantity",
			"laoseis":        "quantity",
			"hind":           "unit_cost",
			"omahind":        "unit_cost",
			"soetushind":     "unit_cost",
			"partii":         "lot_number",
			"partii_nr":      "lot_number",
			"sn":             "serial_number",
			"seerianr":       "serial_number",
			"seeria_nr":      "serial_number",
			"aegumisaeg":     "expiry_date",
			"aegumiskuupäev": "expiry_date",
			"aegumiskuupaev": "expiry_date",
			"selgitus":       "reason",
			"kirjeldus":      "reason",
		},
		KindFixedAssets: {
			"inventar":                   "asset_number",
			"inventari_kood":             "asset_number",
			"inventarikood":              "asset_number",
			"põhivara":                   "asset_number",
			"pohivara":                   "asset_number",
			"nimetus":                    "name",
			"nimi":                       "name",
			"soetusaeg":                  "purchase_date",
			"soetuskuupäev":              "purchase_date",
			"soetuskuupaev":              "purchase_date",
			"soetusmaksumus":             "purchase_cost",
			"soetushind":                 "purchase_cost",
			"seerianr":                   "serial_number",
			"asukoht":                    "location",
			"amortisatsiooni_meetod":     "depreciation_method",
			"kulumi_meetod":              "depreciation_method",
			"kasulik_elu_kuud":           "useful_life_months",
			"eluiga_kuud":                "useful_life_months",
			"jääkväärtus":                "residual_value",
			"jaakvaartus":                "residual_value",
			"akumuleeritud_kulum":        "accumulated_depreciation",
			"kogunenud_kulum":            "accumulated_depreciation",
			"jääkmaksumus":               "book_value",
			"jaakmaksumus":               "book_value",
			"vara_konto":                 "asset_account_code",
			"põhivara_konto":             "asset_account_code",
			"pohivara_konto":             "asset_account_code",
			"kulumi_konto":               "depreciation_expense_account_code",
			"akumuleeritud_kulumi_konto": "accumulated_depreciation_account_code",
			"akumuleeritud_kulum_konto":  "accumulated_depreciation_account_code",
			"hankija":                    "supplier_code",
			"hankija_kood":               "supplier_code",
			"hankijakood":                "supplier_code",
			"hankija_nimi":               "supplier_name",
			"hankijanimi":                "supplier_name",
			"tarnija_nimi":               "supplier_name",
			"tarnijanimi":                "supplier_name",
			"hankija_registrikood":       "supplier_reg_code",
			"hankija_reg_kood":           "supplier_reg_code",
			"hankija_kmkr":               "supplier_vat_number",
			"hankija_kmkr_nr":            "supplier_vat_number",
			"hankija_epost":              "supplier_email",
			"hankija_e_post":             "supplier_email",
		},
		KindOpeningBalances: {
			"konto":     "account_code",
			"deebet":    "debit",
			"kreedit":   "credit",
			"objekt":    "cost_center_code",
			"kulukoht":  "cost_center_code",
			"projekt":   "project_code",
			"selgitus":  "description",
			"kirjeldus": "description",
		},
		KindJournalEntries: {
			"kanne":        "entry_reference",
			"kanne_nr":     "entry_reference",
			"kandenr":      "entry_reference",
			"number":       "entry_reference",
			"dokumendi_nr": "entry_reference",
			"rea_id":       "line_id",
			"kanne_rea_id": "line_id",
			"kande_rea_id": "line_id",
			"aeg":          "entry_date",
			"kuupäev":      "entry_date",
			"kuupaev":      "entry_date",
			"konto":        "account_code",
			"deebet":       "debit",
			"kreedit":      "credit",
			"selgitus":     "line_description",
			"kirjeldus":    "line_description",
			"sisu":         "line_description",
			"valuuta":      "currency",
			"kurss":        "exchange_rate",
			"valuutakurss": "exchange_rate",
		},
		KindEmployees: {
			"töötaja":       "employee_number",
			"tootaja":       "employee_number",
			"töötaja_kood":  "employee_number",
			"tootaja_kood":  "employee_number",
			"isikukood":     "personal_code",
			"eesnimi":       "first_name",
			"perenimi":      "last_name",
			"perekonnanimi": "last_name",
			"pangakonto":    "bank_account",
			"telefon":       "phone",
			"algus":         "start_date",
			"alguskuupäev":  "start_date",
			"alguskuupaev":  "start_date",
			"lõpp":          "end_date",
			"lopp":          "end_date",
			"amet":          "position",
			"osakond":       "department",
			"põhipalk":      "base_salary",
			"pohipalk":      "base_salary",
			"brutopalk":     "base_salary",
		},
		KindPayrollHistory: directoPayrollHistoryAliases("gross_salary"),
		KindLeaveBalances: {
			"töötaja":          "employee_number",
			"tootaja":          "employee_number",
			"töötaja_kood":     "employee_number",
			"tootaja_kood":     "employee_number",
			"isikukood":        "personal_code",
			"aasta":            "year",
			"puudumise_liik":   "absence_type_code",
			"puhkuse_liik":     "absence_type",
			"õigus_päevad":     "entitled_days",
			"oigus_paevad":     "entitled_days",
			"päevi":            "entitled_days",
			"paevi":            "entitled_days",
			"jääk":             "carryover_days",
			"jaak":             "carryover_days",
			"kasutatud":        "used_days",
			"kasutatud_päevad": "used_days",
			"kasutatud_paevad": "used_days",
		},
		KindTSDHistory: directoPayrollHistoryAliases("gross_payment"),
		KindKMDHistory: {
			"aasta":                "year",
			"perioodi_aasta":       "year",
			"kuu":                  "month",
			"perioodi_kuu":         "month",
			"deklaratsiooni_kuu":   "month",
			"deklaratsiooni_aasta": "year",
			"staatus":              "status",
			"deklaratsiooni_olek":  "status",
			"esitatud":             "submitted_at",
			"esitamise_kuupäev":    "submitted_at",
			"esitamise_kuupaev":    "submitted_at",
			"rea_kood":             "row_code",
			"rida":                 "row_code",
			"rea_nr":               "row_code",
			"rea_nimetus":          "description",
			"kirjeldus":            "description",
			"maksustatav_summa":    "tax_base",
			"maksustatav_käive":    "tax_base",
			"maksustatav_kaive":    "tax_base",
			"käibemaks":            "tax_amount",
			"kaibemaks":            "tax_amount",
			"km_summa":             "tax_amount",
			"väljundkäibemaks":     "total_output_vat",
			"valjundkaibemaks":     "total_output_vat",
			"sisendkäibemaks":      "total_input_vat",
			"sisendkaibemaks":      "total_input_vat",
		},
	}
}

func migrationPresetCatalogFileKinds() []FileKind {
	kinds := make([]FileKind, 0, len(fileSpecs))
	for kind := range fileSpecs {
		kinds = append(kinds, kind)
	}
	sort.Slice(kinds, func(i, j int) bool {
		return kinds[i] < kinds[j]
	})
	return kinds
}

func cloneRequiredColumnGroups(groups [][]string) [][]string {
	if len(groups) == 0 {
		return nil
	}
	cloned := make([][]string, 0, len(groups))
	for _, group := range groups {
		cloned = append(cloned, append([]string(nil), group...))
	}
	return cloned
}

func sampleProviderPresetAliases(aliases map[string]string, limit int) []MigrationProviderPresetAlias {
	if len(aliases) == 0 || limit <= 0 {
		return nil
	}
	headers := make([]string, 0, len(aliases))
	for header := range aliases {
		headers = append(headers, header)
	}
	sort.Strings(headers)
	if len(headers) > limit {
		headers = headers[:limit]
	}
	samples := make([]MigrationProviderPresetAlias, 0, len(headers))
	for _, header := range headers {
		samples = append(samples, MigrationProviderPresetAlias{
			SourceHeader:    header,
			CanonicalHeader: aliases[header],
		})
	}
	return samples
}

func meritCommercialDocumentAliases(numberField, dateField string) map[string]string {
	return map[string]string{
		"kuupäev":       dateField,
		"kuupaev":       dateField,
		"kliendi_kood":  "contact_code",
		"kliendikood":   "contact_code",
		"hankija_kood":  "contact_code",
		"hankijakood":   "contact_code",
		"klient":        "contact_name",
		"hankija":       "contact_name",
		"registrikood":  "contact_reg_code",
		"kmkr_nr":       "contact_vat_number",
		"e_post":        "contact_email",
		"epost":         "contact_email",
		"rea_kirjeldus": "line_description",
		"kirjeldus":     "line_description",
		"nimetus":       "line_description",
		"kogus":         "quantity",
		"ühiku_hind":    "unit_price",
		"yhiku_hind":    "unit_price",
		"hind":          "unit_price",
		"käibemaks":     "vat_rate",
		"kaibemaks":     "vat_rate",
		"km":            "vat_rate",
		"artikkel":      "product_code",
		"artikli_kood":  "product_code",
		"toode":         "product_code",
	}
}

func smartAccountsCommercialDocumentAliases(numberField, dateField string) map[string]string {
	aliases := map[string]string{
		"document_no":      numberField,
		"document_number":  numberField,
		"document_date":    dateField,
		"client_no":        "contact_code",
		"client_number":    "contact_code",
		"customer_no":      "contact_code",
		"customer_number":  "contact_code",
		"vendor_no":        "contact_code",
		"vendor_number":    "contact_code",
		"supplier_no":      "contact_code",
		"supplier_number":  "contact_code",
		"client":           "contact_name",
		"customer":         "contact_name",
		"vendor":           "contact_name",
		"supplier":         "contact_name",
		"item_description": "line_description",
		"item_name":        "line_description",
		"qty":              "quantity",
		"vat_percent":      "vat_rate",
		"vat_percentage":   "vat_rate",
		"item_no":          "product_code",
		"item_number":      "product_code",
	}
	if strings.HasPrefix(numberField, "invoice") {
		aliases["invoice_no"] = numberField
		aliases["invoice_number"] = numberField
		aliases["invoice_date"] = dateField
		aliases["document_type"] = "invoice_type"
		aliases["invoice_type"] = "invoice_type"
	}
	return aliases
}

func directoCommercialDocumentAliases(numberField, dateField string) map[string]string {
	return map[string]string{
		"number":        numberField,
		"nr":            numberField,
		"aeg":           dateField,
		"kuupäev":       dateField,
		"kuupaev":       dateField,
		"kliendikood":   "contact_code",
		"kliendi_kood":  "contact_code",
		"klient":        "contact_code",
		"klient_kood":   "contact_code",
		"hankijakood":   "contact_code",
		"hankija_kood":  "contact_code",
		"kliendi_nimi":  "contact_name",
		"hankija_nimi":  "contact_name",
		"nimi":          "contact_name",
		"registrikood":  "contact_reg_code",
		"kmkr":          "contact_vat_number",
		"kmkr_nr":       "contact_vat_number",
		"email":         "contact_email",
		"e_post":        "contact_email",
		"valuuta":       "currency",
		"valuutakurss":  "exchange_rate",
		"kurss":         "exchange_rate",
		"sisu":          "line_description",
		"rea_sisu":      "line_description",
		"rea_kirjeldus": "line_description",
		"kirjeldus":     "line_description",
		"artikkel":      "product_code",
		"artikli_kood":  "product_code",
		"artiklikood":   "product_code",
		"kogus":         "quantity",
		"hind":          "unit_price",
		"ühiku_hind":    "unit_price",
		"yhiku_hind":    "unit_price",
		"allahindlus":   "discount_percent",
		"km":            "vat_rate",
		"kmkood":        "vat_rate",
		"käibemaks":     "vat_rate",
		"kaibemaks":     "vat_rate",
		"müügikonto":    "account_code",
		"myygikonto":    "account_code",
		"konto":         "account_code",
	}
}

func meritPayrollHistoryAliases(grossField string) map[string]string {
	return map[string]string{
		"contractcode":             "employee_number",
		"contract_code":            "employee_number",
		"importcode":               "employee_number",
		"import_code":              "employee_number",
		"personalcode":             "personal_code",
		"personal_code":            "personal_code",
		"employeefullname":         "name",
		"employee_full_name":       "name",
		"month6":                   "period_code",
		"period":                   "period_code",
		"period_code":              "period_code",
		"salarytypename":           "salary_type_name",
		"salary_type_name":         "salary_type_name",
		"sum":                      grossField,
		"totalsum":                 "total_employer_cost",
		"total_sum":                "total_employer_cost",
		"employerunempinsurance":   "unemployment_insurance_employer",
		"employer_unemp_insurance": "unemployment_insurance_employer",
		"socialtax":                "social_tax",
		"social_tax":               "social_tax",
		"vacationreserve":          "vacation_reserve",
		"vacation_reserve":         "vacation_reserve",
		"incometax":                "income_tax",
		"income_tax":               "income_tax",
		"employeeunempinsurance":   "unemployment_insurance_employee",
		"employee_unemp_insurance": "unemployment_insurance_employee",
		"fundedpension":            "funded_pension",
		"funded_pension":           "funded_pension",
	}
}

func directoPayrollHistoryAliases(grossField string) map[string]string {
	return map[string]string{
		"töötaja":                   "employee_number",
		"tootaja":                   "employee_number",
		"töötaja_kood":              "employee_number",
		"tootaja_kood":              "employee_number",
		"isikukood":                 "personal_code",
		"nimi":                      "name",
		"eesnimi":                   "first_name",
		"perenimi":                  "last_name",
		"aasta":                     "period_year",
		"kuu":                       "period_month",
		"perioodi_aasta":            "period_year",
		"perioodi_kuu":              "period_month",
		"periood":                   "period_code",
		"palgaliik":                 "salary_type_name",
		"tasuliik":                  "salary_type_name",
		"bruto":                     grossField,
		"brutopalk":                 grossField,
		"bruto_summa":               grossField,
		"neto":                      "net_salary",
		"netopalk":                  "net_salary",
		"tööandja_kulu":             "total_employer_cost",
		"tooandja_kulu":             "total_employer_cost",
		"sotsiaalmaks":              "social_tax",
		"tulumaks":                  "income_tax",
		"töötuskindlustus_tööandja": "unemployment_insurance_employer",
		"tootuskindlustus_tooandja": "unemployment_insurance_employer",
		"töötuskindlustus_töötaja":  "unemployment_insurance_employee",
		"tootuskindlustus_tootaja":  "unemployment_insurance_employee",
		"kogumispension":            "funded_pension",
		"pension":                   "funded_pension",
		"maksuvaba":                 "basic_exemption",
		"maksustatav_summa":         "taxable_amount",
	}
}
